In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

PyTorch version: 2.3.1+cu121
CUDA available: False


## Creating Tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
#Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix

matrix = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
matrix.ndim

2

In [11]:
matrix[0][0]

tensor(1)

In [12]:
matrix.shape

torch.Size([3, 3])

In [13]:
#Tensor

tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

### Random Tensors

In [16]:
# Random tensor of size(3,4)
random_tensor = torch.rand(20,1,1,3,4)
random_tensor

tensor([[[[[3.2733e-01, 6.5991e-01, 5.6621e-02, 2.5663e-01],
           [1.0773e-01, 2.8838e-01, 8.5367e-01, 2.4640e-01],
           [5.1498e-01, 2.7142e-01, 7.6152e-01, 2.6732e-01]]]],



        [[[[9.3396e-01, 9.9460e-01, 9.6000e-01, 8.0475e-01],
           [7.7163e-01, 8.7058e-01, 5.4731e-01, 2.1138e-01],
           [6.3430e-01, 8.1476e-02, 5.5019e-01, 7.1076e-01]]]],



        [[[[6.5281e-02, 6.2817e-01, 7.3534e-01, 3.8061e-01],
           [2.2008e-01, 8.4406e-01, 4.7450e-01, 6.9831e-01],
           [5.3179e-01, 3.5220e-01, 4.0563e-01, 9.0370e-01]]]],



        [[[[3.8068e-01, 5.1055e-01, 1.1108e-01, 8.7610e-02],
           [7.4835e-01, 6.5769e-01, 1.6512e-01, 2.3589e-01],
           [3.1629e-01, 7.5956e-01, 5.1492e-01, 3.7302e-01]]]],



        [[[[4.7777e-01, 2.0367e-01, 3.3861e-01, 3.2224e-01],
           [4.3490e-01, 7.9693e-01, 3.3437e-01, 5.9115e-01],
           [7.8351e-01, 7.6268e-01, 2.9005e-01, 9.3026e-02]]]],



        [[[[8.8156e-01, 9.2986e-01, 4.5933e-01, 7.1932e

In [17]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
### Zeros and ones - Tensors

zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
### Create tensor of ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
### Create a range of tensors

some_tensor = torch.arange(start=0, end=11, step=3)
some_tensor

tensor([0, 3, 6, 9])

In [22]:
# Creating tensors like

tensor_like = torch.zeros_like(input=some_tensor)
tensor_like

tensor([0, 0, 0, 0])

In [23]:
# Tensor datatypes

float_32_tensor = torch.tensor([3.0, 9.0, 6.0], dtype = None, device = None, requires_grad = False)

float_32_tensor.dtype

torch.float32

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 9., 6.], dtype=torch.float16)

In [26]:
float_16_tensor * float_32_tensor

tensor([ 9., 81., 36.])

In [27]:
print(f"{float_16_tensor.dtype}\n{float_16_tensor.shape}\n{float_16_tensor.device}")

torch.float16
torch.Size([3])
cpu


In [28]:
float_64_tensor = torch.tensor([3.0, 9.0, 6.0], dtype = torch.float64, device = 'cpu', requires_grad = False)

float_64_tensor.dtype

torch.float64

# Tensor operations:
- addition
- subtraction
- multiplication (element wise)
- Division
- matrix multiplication

In [29]:
tensor = torch.tensor([2,4,6])
tensor + 10

tensor([12, 14, 16])

In [30]:
tensor = tensor * 10
tensor

tensor([20, 40, 60])

In [31]:
tensor = tensor / 10
tensor

tensor([2., 4., 6.])

In [32]:
tensor.mul(10)

tensor([20., 40., 60.])

In [33]:
tensor * tensor

tensor([ 4., 16., 36.])

In [34]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 578 µs, sys: 106 µs, total: 684 µs
Wall time: 9.37 ms


tensor(56.)

In [35]:
# Shapes for matix multiplication

tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [36]:
## Find the min, max, sum etc(tensor aggregation)

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [38]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [39]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()  # .mean needs float32

(tensor(45.), tensor(45.))

In [40]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [41]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [42]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [43]:
x[0], x[9]

(tensor(0), tensor(90))

In [73]:
# Reshaping stacking squeezing and unsqueezing tensors

# Reshape - reshape the input to a defined shape
# View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
# Stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)
# Squeeze - removes all 1 dimensions from tensor
# Unsqueeze - add 1 dimension to tensor
# Permute - return the view of the input with dimensions permuted in a cetain way

import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [74]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
# Change the view

z = x.view(2,5)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [52]:
# Changing z changes x - view shares memeory z and x

z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.],
         [ 5.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]))

In [58]:
# Stack tensors on top of each other

x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [86]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape # removes all 1 dimensions

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [89]:
x_reshaped.unsqueeze(dim=1), x_reshaped.unsqueeze(dim=1).shape # adds a 1 dimension to a target tensor at a specific dim

(tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [90]:
# torch.permute - rearranges the dimensions of a tensor in a specified order

x_original = torch.rand(size=(224,224,3))

x_permuted = x_original.permute(2,0,1)

x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [93]:
## Indexing selecting data from tensors

import torch

x = torch.arange(1,11).reshape(1,2,5)
x, x.shape

(tensor([[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]),
 torch.Size([1, 2, 5]))

In [100]:
# Index on the tensor

x[0][0][4]

tensor(5)

In [101]:
# Use ':' to select all of a target dimension

x[:, 0]

tensor([[1, 2, 3, 4, 5]])

In [102]:
x[:,:,1]

tensor([[2, 7]])

In [103]:
x[:, 1, 1]

tensor([7])

In [104]:
x[0,0,:]

tensor([1, 2, 3, 4, 5])

In [107]:
# Python tensors and numpy

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [108]:
#change the value of array

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [109]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [110]:
# Change the tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [111]:
# Reproducbility (trying to take random out of random)

# How a NN learns:
# start with randopm numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again

# To reduce the randomness in NN and pytorch we have the concept of random seed

In [113]:
torch.rand(3,3)

tensor([[0.4709, 0.7669, 0.9470],
        [0.7173, 0.2354, 0.4560],
        [0.9578, 0.9168, 0.8500]])

In [115]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6877, 0.1122, 0.2408, 0.5541],
        [0.0627, 0.3809, 0.2868, 0.4876],
        [0.6266, 0.1887, 0.9390, 0.8570]])
tensor([[0.4181, 0.6634, 0.9306, 0.6652],
        [0.7943, 0.4836, 0.2200, 0.8503],
        [0.7849, 0.0119, 0.7899, 0.7636]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [120]:
# Add random but reproducible tensors

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [1]:
# Running tensors and Pytorch object on the GPUS

# 1. Using Google Collab for a free GPU (options to upgrade as well)
# 2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU
# 3. Use cloud computing - GCP

!nvidia-smi

Tue Jul 30 07:51:57 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
# Check for gpu access with PyTorch
import torch
torch.cuda.is_available()

True

In [4]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [5]:
# Count the number of gpus
torch.cuda.device_count()

1

In [6]:
# Putting tensors and models on the GPU for faster computations

tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# Move tensor to gpu if available

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [8]:
# If tensor is on GPU, cant transform it to numpy

tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [9]:
# To fix the gpu tensor with NumPy we can set it first to cpu

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [10]:
## Exercises

In [12]:
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.5220, 0.5759, 0.8054, 0.6047, 0.3758, 0.6973, 0.7450],
        [0.3165, 0.5689, 0.4501, 0.5187, 0.3242, 0.9330, 0.6063],
        [0.3185, 0.7803, 0.0883, 0.7697, 0.6666, 0.8447, 0.1583],
        [0.5749, 0.2280, 0.6442, 0.8201, 0.7996, 0.3457, 0.6704],
        [0.7022, 0.9942, 0.0140, 0.8793, 0.4617, 0.8470, 0.3726],
        [0.7471, 0.7313, 0.4165, 0.5328, 0.0616, 0.0641, 0.7516],
        [0.7451, 0.9450, 0.7772, 0.6657, 0.7813, 0.3857, 0.9134]])

In [13]:
random_tensor_2 = torch.rand(1,7)

torch.mm(random_tensor,random_tensor_2.T)

tensor([[2.4927],
        [2.1973],
        [2.2433],
        [2.3794],
        [2.7268],
        [2.0047],
        [2.9371]])

In [14]:
SEED = 0

torch.manual_seed(SEED)
random_tensor = torch.rand(7,7)
random_tensor_2 = torch.rand(1,7)

torch.mm(random_tensor,random_tensor_2.T)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [19]:
random_gpu_tensor = torch.cuda.FloatTensor(10, 10).normal_()
random_gpu_tensor

tensor([[ 2.5441, -0.7163, -0.4934,  0.1267,  0.1014, -0.4035,  0.9023,  0.8099,
         -0.6884,  0.1372],
        [ 1.0377,  0.0925, -0.3752, -0.0908,  2.0639, -1.8164, -0.2719,  0.2811,
         -1.0399,  0.7765],
        [ 0.8814,  0.0444, -1.4870,  1.1334,  1.3268, -1.2616,  0.9501, -0.6558,
          0.9098, -0.6290],
        [-0.6587,  2.0811,  1.4151, -0.3091, -0.2055,  2.0562, -0.0490, -0.6361,
         -0.5359, -0.1310],
        [-0.2945,  1.2275,  1.0549,  0.3576,  1.6378, -0.2310,  0.7883, -0.0807,
         -0.3924,  1.2673],
        [ 1.0420, -0.4945, -1.1637,  1.5740,  0.7116,  0.6104,  1.2852, -0.6533,
          1.1171, -1.0067],
        [ 1.2912,  1.6028,  0.1332,  1.0703, -1.1161, -0.8396, -3.6680,  0.8189,
          0.1255, -0.7691],
        [ 0.1552, -0.8782, -0.4734,  0.9690, -1.9985,  0.1030,  0.8580,  0.7625,
         -1.2587, -0.8183],
        [ 1.8004, -0.7912,  0.1998,  1.6940, -1.1763,  0.6664,  0.8763, -1.2800,
          1.1577, -1.9698],
        [ 2.0708, -

In [20]:
torch.manual_seed(1234)
tensor1 = torch.rand(2,3)
tensor2 = torch.rand(2,3)

tensor1_on_gpu = tensor1.to(device)
tensor2_on_gpu = tensor2.to(device)

tensor1_on_gpu, tensor2_on_gpu

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [22]:
values_of_mm = torch.mm(tensor1_on_gpu, tensor2_on_gpu.T)
values_of_mm

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [29]:
values_of_mm.min(), values_of_mm.max()

(tensor(0.3647, device='cuda:0'), tensor(0.5617, device='cuda:0'))

In [28]:
values_of_mm.argmax(), values_of_mm.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [32]:
torch.manual_seed(7)
rand_tns = torch.rand(1,1,1,10)
new_tens = rand_tns.squeeze()
new_tens.shape, rand_tns.shape

(torch.Size([10]), torch.Size([1, 1, 1, 10]))